#!/bin/sh
# gen-bootmenu.sh — generate a platform card's bootmenu.cfg for one tier.
#
# Usage: scripts/gen-bootmenu.sh <platform> <free|public>   (writes stdout)
#
# The free/public split is a CARD split, not a machine-build split: one
# universal platform binary serves both, and the only difference between a
# free card and a public card is this generated menu (plus the asset bundle).
#
#   free   = only machines whose EVERY required asset is free-tier. A machine
#            is absent from the free menu if any asset it needs is public.
#   public = the full roster — the superset "I accept grey-market sourcing"
#            opt-in. A public-tier machine is structurally absent from free.
#
# A machine's tier is DERIVED, never a manifest field: read the machine's
# asset dependencies (MACHINE_ASSETS_* in host/machines.mk), then read each
# asset's tier from scripts/assets.manifest. All-free assets => free machine.
#
# One 'label|defaults-string' per line, in card-roster order (the top line is
# where the picker's cursor first rests). Comment lines start '#'; the boot
# picker's parser ignores them.

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MACHINES_MK="$ROOT/host/machines.mk"
MANIFEST="$ROOT/scripts/assets.manifest"

PLATFORM="${1:?usage: gen-bootmenu.sh <platform> <free|public>}"
TIER="${2:?usage: gen-bootmenu.sh <platform> <free|public>}"

case "$TIER" in
    free|public) ;;
    *) echo "gen-bootmenu.sh: tier must be 'free' or 'public', got '$TIER'" >&2; exit 2 ;;
esac

# Read a machines.mk fact without pulling in the Circle build.
q() { make -s -f "$MACHINES_MK" "print-$1"; }

ROSTER="$(q "PLATFORM_MACHINES_$PLATFORM")"
if [ -z "$ROSTER" ]; then
    echo "gen-bootmenu.sh: unknown platform '$PLATFORM' (see PLATFORMS in machines.mk)" >&2
    exit 2
fi

# The tier of one asset, straight from the manifest's asset stanza.
asset_tier() {
    awk -F'|' -v n="$1" \
        '$1=="asset" && $2==n {print $3; found=1; exit}
         END {if (!found) print "unknown"}' "$MANIFEST"
}

# A machine is free only if every asset it needs is free-tier. An asset the
# manifest does not know is treated as not-free (fail safe: never leak a
# machine into the free menu on a missing tier).
machine_is_free() {
    for a in $(q "MACHINE_ASSETS_$1"); do
        [ "$(asset_tier "$a")" = free ] || return 1
    done
    return 0
}

echo "# pi-mame $PLATFORM card — $TIER tier. Generated by gen-bootmenu.sh; do not edit."
echo "# label|defaults-string, one per line. The top line is where the cursor rests."
for m in $ROSTER; do
    if [ "$TIER" = free ] && ! machine_is_free "$m"; then
        continue
    fi
    printf '%s|%s\n' "$m" "$(q "MACHINE_STRING_$m")"
done
